# Generated by Django 4.2.1 on 2023-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=5),
        ),
    ]
